function sample_param = basef2samparam(basef, instrument_config)
    if basef < 20
        % tone == 0
        sample_param = struct( ...
            "basef", 0, ...
            "harmonics", 1, ...
            "envelope", struct( ...
                "data", [1, 1], ...
                "fs", 1 ...
            ) ...
        );
        return
    end
    indexes = instrument_config.index;
    [~, idx] = min(abs(indexes - basef));
    sample_param = instrument_config.list(idx);
end
